- name: 'get absolute path of library'
  changed_when: false
  command: pwd
  args:
    chdir: 'library'
  register: directory_path_output

- name: set absolute path of library
  set_fact:
    abs_library_path: '{{ directory_path_output.stdout }}'

- name: create the initial virtualenv
  pip:
    requirements: '{{ abs_library_path }}/requirements.txt'
    virtualenv: '{{ virtualenv }}'
    virtualenv_command: /usr/bin/python3 -m venv